FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    python3 \
    python3-pip \
    python3-dev \
    ffmpeg \
    openssl \
    git \
    wget \
    curl \
    unzip \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libnss3 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /etc/ssl/private && \
    openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 \
    -keyout /etc/ssl/private/key.pem -out /etc/ssl/private/cert.pem \
    -subj "/C=TR/ST=KOCAELI/O=NovaVision AI/CN=novavision.ai"

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y google-chrome-stable && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


ENV PIP_DEFAULT_TIMEOUT=1000
ENV PIP_RETRIES=5
ENV PIP_NO_CACHE_DIR=1

WORKDIR /opt/project

COPY requirements.prod /opt/project/

RUN python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

RUN python3 -m pip install vllm==0.10.1.1

RUN python3 -m pip install cupy-cuda12x==13.6.0

RUN python3 -m pip install ultralytics==8.3.75

RUN python3 -m pip install --no-cache-dir -r requirements.prod

COPY . /opt/project

RUN chmod +x /opt/project/entrypoint.sh

ENTRYPOINT ["/bin/bash", "/opt/project/entrypoint.sh"]
